#!/bin/sh

# Slackware build script for apache-tomcat

# Copyright 2010  Vincent Batts, vbatts@hashbangbash.com, http://hashbangbash.com/
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR ''AS IS'' AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO
# EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
# OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
# ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


PRGNAM=apache-tomcat
VERSION=6.0.24
ARCH=${ARCH:-i486}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}

TEAM=$(echo $PRGNAM | cut -d- -f1)
PROJECT=$(echo $PRGNAM | cut -d- -f2)

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

set -e

if [ "$ARCH" = "i686" ]; then
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "x86_64" ]; then
  LIBDIRSUFFIX="64"
elif [ "$ARCH" = "s390" ]; then
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "arm" ]; then
  LIBDIRSUFFIX=""
fi

# Bail if user or group isn't valid on your system
if ! grep ^tomcat: /etc/passwd 2>&1 > /dev/null; then

cat << EOF

  You must have a tomcat user to run this script

  # groupadd -g 231 tomcat
  # useradd -u 231 -d /srv/tomcat -s /bin/sh -g tomcat tomcat

EOF
  exit
fi

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $PRGNAM-$VERSION
tar xvf $CWD/$PRGNAM-$VERSION.tar.gz
cd $PRGNAM-$VERSION
chown -R root:root .
find . \
 \( -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 \) \
 -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
 -exec chmod 644 {} \;

mkdir -p $PKG/etc/rc.d
cat $CWD/rc.$PROJECT > $PKG/etc/rc.d/rc.$PROJECT.new
chmod 0755 $PKG/etc/rc.d/rc.$PROJECT.new

mkdir -p $PKG/srv/$PROJECT
cp -a bin conf lib logs temp webapps work \
  $PKG/srv/$PROJECT/

rm $PKG/srv/$PROJECT/bin/*.bat

cat > $PKG/srv/$PROJECT/bin/setenv.sh <<EOF
export JAVA_HOME="/usr/lib${LIBDIRSUFFIX}/java"
export JAVA_OPTS="-Xms512m -Xmx1024m -XX:MaxPermSize=512m -Xss128k"
export CATALINA_OPTS="\$CATALINA_OPTS "

EOF

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cp -a RUNNING.txt LICENSE NOTICE RELEASE-NOTES \
  $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc
cat $CWD/doinst.sh > $PKG/install/doinst.sh

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.tgz

