#!/bin/sh

# Slackware build script for fcgi

# Written by Vincent Batts, vbatts@batts.mine.nu

set -e

PRGNAM=fcgi
VERSION=2.4.0
PRGNAM2=mod_fcgid
VERSION2=2.2
ARCH=${ARCH:-i486}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}
CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}
HTTPD_DIR=/usr/lib/httpd/

if [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
fi

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $PRGNAM-$VERSION
tar zxvf $CWD/$PRGNAM-$VERSION.tar.gz
cd $PRGNAM-$VERSION
tar zxvf $CWD/$PRGNAM2.$VERSION2.tgz
chown -R root:root .
find . \
 \( -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 \) \
 -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
 -exec chmod 644 {} \;

# first build and install the fcgi stuff
CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
./configure \
  --prefix=/usr \
  --sysconfdir=/etc \
  --localstatedir=/var \
  --mandir=/usr/man

make
make install DESTDIR=$PKG

# move into the mod_fcgid directory
cd $PRGNAM2.$VERSION2
mkdir -p $PKG/$HTTPD_DIR/modules
ln -s $HTTPD_DIR/build $PKG/$HTTPD_DIR/
CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
make top_dir=$HTTPD_DIR
cp ./.libs/mod_fcgid.so $PKG/$HTTPD_DIR/modules
rm $PKG/$HTTPD_DIR/build

mkdir -p $PKG/etc/httpd/extra
cp $CWD/httpd-fcgi.conf $PKG/etc/httpd/extra/

( cd $PKG
  find . | xargs file | grep "executable" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
  find . | xargs file | grep "shared object" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
)

cd ..
mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM2-$VERSION2/
cp -a LICENSE.TERMS doc/ $PKG/usr/doc/$PRGNAM-$VERSION
cd $PRGNAM2.$VERSION2
cp -a AUTHOR COPYING INSTALL.txt ChangeLog $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM2-$VERSION2
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.tgz
