#!/bin/sh

# Slackware build script for vimoutliner

# Written by Vincent Batts, vbatts@hashbangbash.com

PRGNAM=vimoutliner
VERSION=${VERSION:-0.3.4}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}

# Automatically determine the architecture we're building on:
if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i486 ;;
    arm*) ARCH=arm ;;
    # Unless $ARCH is already set, use uname -m for all other archs:
       *) ARCH=$( uname -m ) ;;
  esac
fi

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

if [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
  LIBDIRSUFFIX="64"
else
  SLKCFLAGS="-O2"
  LIBDIRSUFFIX=""
fi

set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $PRGNAM-$VERSION
tar xvf $CWD/$PRGNAM-$VERSION.tar.gz
cd $PRGNAM-$VERSION
chown -R root:root .
find . \
 \( -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 \) \
 -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
 -exec chmod 644 {} \;

# i can not imagine this being different than /usr/share/vim, but who knows ...
runtimepath=$(vim --version | grep "fall-back for .VIM" | cut -d : -f 2 | tr -d ' ' | tr -d \")

mkdir -p $PKG/${runtimepath}/vimfiles/{syntax,ftplugin,ftdetect,doc,colors}
cp syntax/vo_base.vim $PKG/${runtimepath}/vimfiles/syntax/
cp ftplugin/vo_base.vim $PKG/${runtimepath}/vimfiles/ftplugin/
cp ftdetect/vo_base.vim $PKG/${runtimepath}/vimfiles/ftdetect/
cp doc/vo_readme.txt $PKG/${runtimepath}/vimfiles/doc/
cp colors/vo_dark.vim $PKG/${runtimepath}/vimfiles/colors/
cp colors/vo_light.vim $PKG/${runtimepath}/vimfiles/colors/

mkdir -p $PKG/usr/bin
cp scripts/vo_maketags.pl $PKG/usr/bin/vo_maketags
cp add-ons/scripts/otl2html.py $PKG/usr/bin/otl2html


mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cp -a \
  CHANGELOG LICENSE INSTALL VERSION vimoutlinerrc add-ons \
  $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc
cat $CWD/doinst.sh > $PKG/install/doinst.sh

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
