#!/bin/sh
# Slackware build script for aptana-studio
# Written by Vincent Batts, vbatts@hashbangbash.com

PRGNAM=aptana-studio
VERSION=${VERSION:-1.1}
ARCH=${ARCH:-i486}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

set -e

rm -rf $PKG
mkdir -p $TMP $PKG/usr/lib $OUTPUT
cd $PKG/usr/lib
unzip $CWD/Aptana_Studio_Setup_Linux.zip
mv aptana $PRGNAM-$VERSION
chown -R root:root .

patch $PKG/usr/lib/$PRGNAM-$VERSION/configuration/config.ini $CWD/config.ini.diff

mkdir -p $PKG/usr/bin
cp -a $CWD/${PRGNAM}.sh $PKG/usr/bin/$PRGNAM
chmod 755 $PKG/usr/bin/$PRGNAM

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cd $PKG/usr/lib/$PRGNAM-$VERSION
cp -a about.html about_files full_uninstall.txt version.txt $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.tgz
