#!/bin/sh

CWD=$(pwd)
PRGNAM=dirvish
VERSION=1.2.1
TMP=/tmp
WORKDIR=$TMP/$PRGNAM-$VERSION
PKG=$TMP/package-$PRGNAM
ARCH=noarch
BUILD=1_vb
PKGTYPE=txz

cd $TMP
rm -rf $WORKDIR $PKG
mkdir -p $WORKDIR $PKG/install
cd $WORKDIR
tar xf $CWD/$PRGNAM-$VERSION.tgz

eval $(grep -e '^EXECUTABLES' install.sh)
eval $(grep -e '^MANPAGES' install.sh)

BINDIR="/usr/sbin"
CONFDIR="/etc/dirvish"
MANDIR="/usr/man"
PREFIX="/usr"

HEADER="#!$(which perl)

\$CONFDIR = \"$CONFDIR\";

"

for f in $EXECUTABLES
do
	echo "$HEADER" >$f
	cat $f.pl >>$f
	cat loadconfig.pl >>$f
	chmod 755 $f
done

mkdir -p $PKG/$BINDIR
mkdir -p $PKG/$MANDIR
for f in $EXECUTABLES
do
	cp $f $PKG/$BINDIR/$f
	chmod 755 $PKG/$BINDIR/$f
done
for f in $MANPAGES
do
	s=`expr "$f" : '.*\(.\)$'`
	if [ ! -d "$PKG/$MANDIR/man$s" ]
	then
		mkdir -p "$PKG/$MANDIR/man$s"
	fi
	cp $f $PKG/$MANDIR/man$s/$f
	gzip $PKG/$MANDIR/man$s/$f
	chmod 644 $PKG/$MANDIR/man$s/$f.gz
done

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cp -a CHANGELOG COPYING FAQ.html \
  INSTALL RELEASE.html TODO.html \
  $PKG/usr/doc/$PRGNAM-$VERSION/

cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG

/sbin/makepkg -l y -c y $TMP/$PRGNAM-$VERSION-$ARCH-$BUILD.$PKGTYPE
