#!/bin/sh

# Slackware build script for xalan
# Written by Vincent Batts, vbatts@hashbangbash.com

set -e

PRGNAM=xalan
VERSION=2.7.1
DVER=j_2_7_1
ARCH=${ARCH:-i486}
ANT_HOME=${ANT_HOME:-/usr/share/ant}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}
CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf ${PRGNAM}-${DVER}
tar xvf $CWD/${PRGNAM}-${DVER}-bin-2jars.tar.gz
cd ${PRGNAM}-${DVER}
chown -R root:root .

mkdir -p $PKG/$ANT_HOME/lib/ $PKG/usr/share/java
cp $PRGNAM.jar serializer.jar xsltc.jar $PKG/$ANT_HOME/lib/
cd $PKG/usr/share/java
ln -s ../../../$ANT_HOME/lib/$PRGNAM.jar
ln -s ../../../$ANT_HOME/lib/serializer.jar
ln -s ../../../$ANT_HOME/lib/xstlc.jar
cd -

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
zip -9 -r $PKG/usr/doc/$PRGNAM-$VERSION/docs.zip docs/
cp -a samples/ readme.html LICENSE.txt NOTICE.txt $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.tgz
