#!/bin/sh

# Slackware build script for mysql-connector-java
# Written by Vincent Batts, vbatts@hashbangbash.com

PRGNAM=mysql-connector-java
VERSION=${VERSION:-5.1.10}
ARCH=noarch
BUILD=${BUILD:-1}
TAG=${TAG:-_vb}

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $PRGNAM-$VERSION
tar xvf $CWD/$PRGNAM-$VERSION.tar.gz
cd $PRGNAM-$VERSION
chown -R root:root .
find . \
 \( -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 \) \
 -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
 -exec chmod 644 {} \;

mkdir -p $PKG/usr/share/java
cp $PRGNAM-$VERSION-bin.jar $PKG/usr/share/java

mkdir -p $PKG/etc/profile.d
cat >> $PKG/etc/profile.d/$PRGNAM.sh << xxEOFxx
#/!bin/sh
export set CLASSPATH=/usr/share/java/$PRGNAM-$VERSION-bin.jar:\$CLASSPATH
xxEOFxx
cat >> $PKG/etc/profile.d/$PRGNAM.csh << xxEOFxx
setenv CLASSPATH /path/$PRGNAM-$VERSION-bin.jar:\$CLASSPATH
xxEOFxx
chmod +x $PKG/etc/profile.d/*

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
zip -9 -r $PKG/usr/doc/$PRGNAM-$VERSION/src.zip build.xml src/
cp -a \
  CHANGES COPYING EXCEPTIONS-CONNECTOR-J README* docs \
  $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.tgz
